name: Fetch Related Paper via Gemini
on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2am UTC
  workflow_dispatch:

jobs:
  fetch-paper:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Fetch paper via Gemini
        run: python test/test_gemini_fetch.py
      - name: Commit new paper
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add papers/*.md
          git commit -m "Add new paper from Gemini API" || echo "No changes"
          git push
